[package]
name = "rbm"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "entity", "migration", "backend"]

[dependencies]
backend = { path = "backend" }
migration = { path = "migration" }
axum = "0.6.4"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
sea-orm-migration = "0.11.0"