[package]
name = "backend"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
entity = { path = "../entity" }
rest-api = { path = "../rest-api" }
async-trait = "0.1.64"
axum = "0.6.4"
sea-orm = { version = "0.11.0", features = ["runtime-tokio-rustls", "sqlx-postgres"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
