[package]
name = "backend"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
entity = { path = "../entity" }
common = { path = "../common" }
rest-api = { path = "../rest-api", features = ["server"] }
async-trait = "0.1.64"
axum = "0.6.4"
sea-orm = { version = "0.11.0", features = ["runtime-tokio-rustls", "sqlx-postgres"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
qrcode-generator = "4.1.7"
log = "0.4.17"
webpage = "1.5.0"
chrono = "0.4.23"
argon2 = "0.4.1"
secrecy = "0.8.0"
axum-sessions = "0.4.1"